version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - antfu
  - bumpp
  - defu
  - execa
  - guiiai
  - Infobar
  - KHTML
  - logg
  - mdast
  - neuri
  - noancestors
  - ofetch
  - openai
  - prismarine
  - reactjs
  - serpapi
  - shiki
  - shikijs
  - Streamable
  - testdata
  - typeschema
  - valibot
  - vitepress
  - vuejs
  - xsai
ignoreWords: []
import: []
