version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aichat
  - airi
  - antfu
  - bumpp
  - convo
  - defu
  - execa
  - guiiai
  - Infobar
  - KHTML
  - logg
  - mcdata
  - mdast
  - messagestr
  - mineflayer
  - mooshroom
  - neko
  - neuri
  - noancestors
  - ofetch
  - openai
  - prismarine
  - reactjs
  - serpapi
  - shiki
  - shikijs
  - Streamable
  - testdata
  - typeschema
  - valibot
  - vitepress
  - vuejs
  - xsai
  - OneLinerable
ignoreWords: []
import: []
